### ISSUE TITLE
Pourquoi utiliser les URL des requêtes GetCapabilities ?

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mdchecker#1]
Les tests du plugin testDigitalTransferOptions.py recherchent la présence des URL de requêtes GetCapabilities dans les fiches de métadonnées :
https://github.com/geobretagne/mdchecker/blob/master/mdchecker/plugins/testDigitalTransferOptions.py#L25

Au niveau de GéoPicardie, l'URL renseignée est celle du service et non celle de la requête GetCapabilities. Pour choisir l'URL de la requête GetCapabilities ? Est-ce que cela vient d'une contrainte de geOrchestra ou d'une contrainte liée au rapportage INSPIRE ? ou d'autre chose ?

**Comment by fphg** [comment]
Nous voulons (et c'est je crois partagé par INSPIRE FR) que les URLs soient résolvables. Et l'URL du service peut être toute autre que celle des capacités.

**Comment by bchartier** [comment]
Ok. Compris. Merci.
