### ISSUE TITLE
ne fonctionne plus derrière un proxy http

### ISSUE THREAD

**Issue by fphg** [geobretagne/mdchecker#11]
La version owslib utilise requests qui dépend d'urllib3. La configuration d'un proxy sortant diffère de urllib2. La configuration proposée dans app.cfg

Workaround, urllib3 est sensible à la variable d'environnement http_proxy

**Comment by bchartier** [comment]
> app.cfg

tu veux dire app.json je suppose.

**Comment by fphg** [comment]
oui

**Comment by fphg** [comment]
3aa08fd0e0b9613ab6e35a50c8f2b679de2b5f99 pour utiliser un proxy sortant
