### ISSUE TITLE
pagination pour export json/csv ?

### ISSUE THREAD

**Issue by fphg** [geobretagne/mdchecker#16]
La pagination pour le quick test html est pratique.
Les sorties csv et json empruntent la même route, mais pas de pagination -> limité au max records per page. Comment permettre un export pour tout le catalogue ?

**Comment by bchartier** [comment]
Quand on traite la requête pour csv et json, il faudrait ne pas appliquer la valeur par défaut de maxharvest utilisée là :
https://github.com/geobretagne/mdchecker/blob/master/app/mdchecker/main.py#L423

Ensuite, il faudrait sûrement ajouter un paramètre à la fonction run_unrecorded_tests pour lui indiquer que l'on souhaite récupérer tous les enregistrements
https://github.com/geobretagne/mdchecker/blob/master/app/mdchecker/main.py#L215

Avec un peu de chance cela pourrait suffire.

**Comment by bchartier** [comment]
@fphg : j'ai rapidement fait des tests sur l'export CSV et JSON de mdchecker sur le catalogue de GéoPicardie. J'ai l'impression que l'intégralité du catalogue est exporté sans souci. La quantitié d'enregistrement est peut-être limitée par le paramètre maxmaxharvest mais pour moi c'est largement suffisant. Est-ce qu'on a besoin de faire quelque chose de plus ?

**Comment by bchartier** [comment]
Confirmé par https://github.com/geobretagne/mdchecker/blob/master/app/mdchecker/main.py#L501

``` python
    # bulk export
    if args['format'] in ['json', 'csv']:
        args['maxharvest'] = cfg['maxmaxharvest']
```

**Comment by fphg** [comment]
Confirmé oui. C'est bien à cela que sert maxmaxharvest - protection pour le serveur.
Pas besoin de faire plus
