### ISSUE TITLE
il manque une license

### ISSUE THREAD

**Issue by fvanderbiest** [geobretagne/mdchecker#19]

**Comment by bchartier** [comment]
MIT me semble être la licence pertinente pour quelqu'un comme moi qui m'en fous un peu de ce que font les autres gens de mes outils. Ceci dit, c'est plutôt à GéoBretagne de choisir.

**Comment by fphg** [comment]
une licence geOrchestra compatible, pourquoi pas la même

**Comment by bchartier** [comment]
> une licence geOrchestra compatible, pourquoi pas la même

Pas idiot.
Pour geOrchestra c'est GPL 3.
C'est pas ma tasse thé mais faites comme si je n'avais pas d'opinion ;)

**Comment by bchartier** [comment]
Chers géobretons et autres membres du projet :
je colle ça : http://choosealicense.com/licenses/gpl-3.0/
ou ça : http://choosealicense.com/licenses/mit/
?

**Comment by bchartier** [comment]
ou rien du tout ?

**Comment by fphg** [comment]
Le 27/09/2016 10:32, Benjamin C. a écrit :

> ou rien du tout ?

GPLV3 je pense

## 

Fabrice Phung

**Comment by bchartier** [comment]
Fait : 56bf4e9
