### ISSUE TITLE
Tests étonnants dans testInspireKeyword.py

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mdchecker#2]
La fin du plugin consacré au thème INSPIRE parait plutôt étonnant :
https://github.com/geobretagne/mdchecker/blob/master/mdchecker/plugins/testInspireKeyword.py#L73

Le test sur la licence ressemble à un copier/coller d'un autre plugin (testLicence.py) et le test MdUnitTestSpatial ne semble rien faire (instruction pass).

S'agit-il d'une erreur ?

**Comment by fphg** [comment]
Oui. Tous les prototypes de test étaient dans un unique fichier. Ces deux ont été oubliés quand les tests ont été éclatés dans plusieurs fichiers. Il faut les ôter.
Pour ma part j'y reviendrai avant le prochain sprint, donc pas tout de suite.

**Comment by bchartier** [comment]
J'aurai peut-être des éléments à apporter.

**Comment by fphg** [comment]
Merci Benjamin. Help yourself :) Y compris sur les plugins existants.
La difficulté est de ne pas générer trop de faux positifs, ou trop de tests locaux. Notre objectif est 1/ d'améliorer le score de rapportage et 2/ que la SDI fonctionne correctement.

**Comment by bchartier** [comment]
Je vais essayer de respecter cette ligne directrice.

**Comment by bchartier** [comment]
Corrigé avec cfae77e
