### ISSUE TITLE
Compatibilité Windows

### ISSUE THREAD

**Issue by Guts** [geobretagne/mdchecker#27]
[uwsgi](http://uwsgi-docs.readthedocs.io/en/latest/SupportedPlatforms.html) n'est pas disponible sur Windows ou du moins très difficilement dans le cadre d'une utilisation en virtualenv (Testé sur Windows 8.1 pour info).

Cela n'empêche pas de fonctionner via un simple `python runserver.py`, comme indiqué dans INSTALL.MD d'ailleurs.

~Je suggère de l'indiquer dans la documentation, voir le README.~

Autant pour moi, c'est indiqué dans INSTALL.md. Mais du coup, je trouve dommage de ne pas être compatible Windows à cause d'une seule dépendance.

**Comment by bchartier** [comment]
Oui, on est d'accord.
Tu m'as dit avoir réussi à le faire fonctionner sur ton poste Windows. C'est toujours vrai ?
Si c'est le cas, on peut :
- créer un requirements.txt spécifique à Windows
- modifier le INSTALL.md en y indiquant où trouver les modules Python compilés pour Windows.

**Comment by bchartier** [comment]
Ce ticket est lié à celui-ci : #25

**Comment by Guts** [comment]
Je prépare une PR pour MAJ INSTALL.md et ajouter un requirements dédié, mais les packages wheels pour Flask et son module SQLalchemy sont trouvables que par un rechercher dans le site de Christoph Golke.

Du coup, j'ai regroupé les libs dans un zip. Il ne pèse que 1,8 Mo. Je sais que c'est pas une bonne pratique mais bon je le laisse ici, ça pourra aider les nécessiteux :)

[libs.zip](https://github.com/geobretagne/mdchecker/files/604980/libs.zip)

**Comment by bchartier** [comment]
> Je prépare une PR pour MAJ INSTALL.md et ajouter un requirements dédié,

Merci

> mais les packages wheels pour Flask et son module SQLalchemy sont trouvables que par un rechercher dans le site de Christoph Golke.

On peut mettre le lien vers http://www.lfd.uci.edu/~gohlke/pythonlibs/ dans INSTALL.md. C'est déjà pas mal.

> Du coup, j'ai regroupé les libs dans un zip. Il ne pèse que 1,8 Mo. Je sais que c'est pas une bonne pratique mais bon je le laisse ici, ça pourra aider les nécessiteux :)

Oui, je suis d'accord avec tout cela.

**Comment by Guts** [comment]
La dockerisation devrait résoudre ce souci.
