### ISSUE TITLE
Dockeriser mdchecker

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mdchecker#8]
Dockeriser mdchecker pour :
- simplifier le déploiement
- faciliter l'intégration dans l'architecture dockerisée de georchestra

**Comment by bchartier** [comment]
Je me suis trompé de ticket dans mon commit... quel lourdot !
@fphg : tu sais comment corriger mon commit pour référencer le bon ticket ?

**Comment by bchartier** [comment]
Je propose qu'on s'inspire des projets suivants pour faire un container pour mdchecker :
- https://github.com/p0bailey/docker-flask
- https://github.com/tiangolo/uwsgi-nginx-flask-docker
  Les 2 utilisent uwsgi et nginx

@fphg  : Est-ce que l'on crée le docker-file et docker-compose dans le présent projet ou est-ce que l'on crée un projet à côté ?
Si c'est dans le même projet, on pourra simplement utiliser la commande COPY dans le dockerfile pour déployer l'appli dans le container mais il faudra sûrement ajouter un niveau d'arborescence supplémentaire au projet actuel.

**Comment by fphg** [comment]
@bchartier dans le même projet, très bien

**Comment by fphg** [comment]
https://help.github.com/articles/changing-a-commit-message/
"We strongly discourage force pushing..."
.. laisse tomber

**Comment by bchartier** [comment]
> https://help.github.com/articles/changing-a-commit-message/
> "We strongly discourage force pushing..."
> .. laisse tomber

ok

**Comment by bchartier** [comment]
> @bchartier dans le même projet, très bien

parfait, j'ai commencé à faire des tests en local

**Comment by bchartier** [comment]
J'ai fait les ajustements pour créer container docker (ce n'est pas encore optimisé mais au moins on a un container Docker avec NGINX, USWGI et l'appli qui tourne).
Je pousse cela dans master ?

**Comment by bchartier** [comment]
Voilà j'ai poussé le dockerfile et tout le reste dans master (moi non plus je n'aime pas trop maintenir 2 branches).

Ce qu'il manque encore (à voir peut-être dans d'autres tickets) :
- création d'un volume pour la base de données (pour pouvoir la sauvegarder ou la conserver quand on met à jour le container)
- création d'un volume pour les fichiers de config ou paramétrage du dockerfile avec des variables d'environnement pour personnaliser le container au moment de sa création
- mise à jour du readme.md et du install.md pour décrire la création du container

**Comment by fvanderbiest** [comment]
J'ai une erreur au build:

```
Step 9 : RUN python /var/www/app/create_db.py
 ---> Running in 8276c5a9d65a
/usr/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[2016-09-16 09:08:54,708] ERROR in main: cant read or write mdchecker/conf/app.json, using defaults
ERROR:mdchecker:cant read or write mdchecker/conf/app.json, using defaults
```

Apparemment, ça passe quand même.

**Comment by bchartier** [comment]
Oui, ça passe quand-même.
Cette erreur n'est pas spécifique à Docker. On a le même message quand on lance l'appli avec le serveur web intégré de Flask. Il faut qu'on regarde cela.

J'ai créé le ticket #17 pour cette anomalie.

**Comment by bchartier** [comment]
Est-ce qu'on ferme ce ticket ?

**Comment by fvanderbiest** [comment]
+1
